  - name: Install global Ruby gems.
    gem:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
      version: "{{ item.version | default(omit) }}"
      user_install: false
      executable: "{{ item.executable | default(omit) }}"
    loop: "{{ gem_packages }}"
